In [ ]:
import tensorflow as tf
import numpy as np
import os
import time

In [ ]:
path_to_file=tf.keras.utils.get_file('shakespeare.txt','https://storage.googleapis.com/download.tensorflow.org/data/shakespeare.txt')

1122304/1115394 [==============================] - 0s 0us/step


In [ ]:
path_to_file

'/root/.keras/datasets/shakespeare.txt'

In [ ]:
import pandas as pd


In [ ]:
text=open(path_to_file,'rb').read().decode(encoding='utf-8')


In [ ]:
print('Length of text: {} characters'.format(len(text)))


Length of text: 1115394 characters


In [ ]:
print(text[:250])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?

All:
Resolved. resolved.

First Citizen:
First, you know Caius Marcius is chief enemy to the people.



In [ ]:
vocab=sorted(set(text))

In [ ]:
vocab

['\n',
 ' ',
 '!',
 '$',
 '&',
 "'",
 ',',
 '-',
 '.',
 '3',
 ':',
 ';',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z']

In [ ]:
char2idx={u:i for i,u in enumerate(vocab)}
idx2char=np.array(vocab)
text_as_int=np.array([char2idx[c] for c in text])

In [ ]:
len(text_as_int)

1115394

In [ ]:
seq_length=100
examples_per_epoch=len(text)//(seq_length+1)
char_dataset=tf.data.Dataset.from_tensor_slices(text_as_int)

In [ ]:
next(iter(char_dataset))

<tf.Tensor: shape=(), dtype=int64, numpy=18>

In [ ]:
sequences=char_dataset.batch(seq_length+1,drop_remainder=True)
for item in sequences.take(5):
  print(len(item))
  break

101


In [ ]:
len(text_as_int)

1115394

In [ ]:
def split_input_target(chunk):
  input_text=chunk[:-1]
  target_text=chunk[1:]
  return input_text,target_text
dataset=sequences.map(split_input_target)

In [ ]:
next(iter(dataset))

(<tf.Tensor: shape=(100,), dtype=int64, numpy=
 array([18, 47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43,
        44, 53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39,
        52, 63,  1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1,
        51, 43,  1, 57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31,
        54, 43, 39, 49,  6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56,
        57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 37, 53, 59])>,
 <tf.Tensor: shape=(100,), dtype=int64, numpy=
 array([47, 56, 57, 58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 14, 43, 44,
        53, 56, 43,  1, 61, 43,  1, 54, 56, 53, 41, 43, 43, 42,  1, 39, 52,
        63,  1, 44, 59, 56, 58, 46, 43, 56,  6,  1, 46, 43, 39, 56,  1, 51,
        43,  1, 57, 54, 43, 39, 49,  8,  0,  0, 13, 50, 50, 10,  0, 31, 54,
        43, 39, 49,  6,  1, 57, 54, 43, 39, 49,  8,  0,  0, 18, 47, 56, 57,
        58,  1, 15, 47, 58, 47, 64, 43, 52, 10,  0, 37, 53, 59,  1])>)

In [ ]:
for input_example, target_example in  dataset.take(1):
    print('Input data: ', repr(''.join(idx2char[input_example.numpy()])))
    print('Target data:', repr(''.join(idx2char[target_example.numpy()])))

Input data:  'First Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou'
Target data: 'irst Citizen:\nBefore we proceed any further, hear me speak.\n\nAll:\nSpeak, speak.\n\nFirst Citizen:\nYou '


In [ ]:
idx2char

array(['\n', ' ', '!', '$', '&', "'", ',', '-', '.', '3', ':', ';', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
       'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z'],
      dtype='<U1')

In [ ]:
char2idx

{'\n': 0,
 ' ': 1,
 '!': 2,
 '$': 3,
 '&': 4,
 "'": 5,
 ',': 6,
 '-': 7,
 '.': 8,
 '3': 9,
 ':': 10,
 ';': 11,
 '?': 12,
 'A': 13,
 'B': 14,
 'C': 15,
 'D': 16,
 'E': 17,
 'F': 18,
 'G': 19,
 'H': 20,
 'I': 21,
 'J': 22,
 'K': 23,
 'L': 24,
 'M': 25,
 'N': 26,
 'O': 27,
 'P': 28,
 'Q': 29,
 'R': 30,
 'S': 31,
 'T': 32,
 'U': 33,
 'V': 34,
 'W': 35,
 'X': 36,
 'Y': 37,
 'Z': 38,
 'a': 39,
 'b': 40,
 'c': 41,
 'd': 42,
 'e': 43,
 'f': 44,
 'g': 45,
 'h': 46,
 'i': 47,
 'j': 48,
 'k': 49,
 'l': 50,
 'm': 51,
 'n': 52,
 'o': 53,
 'p': 54,
 'q': 55,
 'r': 56,
 's': 57,
 't': 58,
 'u': 59,
 'v': 60,
 'w': 61,
 'x': 62,
 'y': 63,
 'z': 64}

In [ ]:
for i, (input_idx, target_idx) in enumerate(zip(input_example[:5], target_example[:5])):
    print("Step {:4d}".format(i))
    print("  input: {} ({:s})".format(input_idx, repr(idx2char[input_idx])))
    print("  expected output: {} ({:s})".format(target_idx, repr(idx2char[target_idx])))

Step    0
  input: 18 ('F')
  expected output: 47 ('i')
Step    1
  input: 47 ('i')
  expected output: 56 ('r')
Step    2
  input: 56 ('r')
  expected output: 57 ('s')
Step    3
  input: 57 ('s')
  expected output: 58 ('t')
Step    4
  input: 58 ('t')
  expected output: 1 (' ')


In [ ]:
BATCH_SIZE=64
BUFFER_SIZE=10000
dataset=dataset.shuffle(BUFFER_SIZE).batch(BATCH_SIZE,drop_remainder=True)
dataset

<BatchDataset shapes: ((64, 100), (64, 100)), types: (tf.int64, tf.int64)>

In [ ]:
vocab_size=len(vocab)
embedding_dim=256
rnn_units=1024

In [ ]:
def build_model(vocab_size,embedding_dim,rnn_units,batch_size):
  model=tf.keras.Sequential([
      tf.keras.layers.Embedding(vocab_size,embedding_dim,batch_input_shape=[batch_size,None]),
      tf.keras.layers.GRU(rnn_units,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'),
      tf.keras.layers.Dense(vocab_size)
  ])
  return model
  

In [ ]:
next(iter(dataset))

(<tf.Tensor: shape=(64, 100), dtype=int64, numpy=
 array([[60, 43, 56, ..., 63, 53, 59],
        [56,  1, 50, ...,  1, 40, 59],
        [47, 50, 50, ..., 15, 23, 21],
        ...,
        [58, 46, 43, ..., 46, 39, 58],
        [ 6,  1, 53, ...,  1, 41, 53],
        [ 0, 21,  1, ..., 21, 33, 31]])>,
 <tf.Tensor: shape=(64, 100), dtype=int64, numpy=
 array([[43, 56,  1, ..., 53, 59, 56],
        [ 1, 50, 53, ..., 40, 59, 56],
        [50, 50,  1, ..., 23, 21, 26],
        ...,
        [46, 43,  1, ..., 39, 58,  1],
        [ 1, 53, 56, ..., 41, 53, 59],
        [21,  1, 39, ..., 33, 31, 10]])>)

In [ ]:
model=build_model(vocab_size=len(vocab),embedding_dim=embedding_dim,rnn_units=rnn_units,batch_size=BATCH_SIZE)

In [ ]:
for input_example_batch,target_example_batch in dataset.take(1):
  example_batch_predictions=model(input_example_batch)
  print(example_batch_predictions.shape)

(64, 100, 65)


In [ ]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding (Embedding)        (64, None, 256)           16640     
_________________________________________________________________
gru (GRU)                    (64, None, 1024)          3938304   
_________________________________________________________________
dense (Dense)                (64, None, 65)            66625     
Total params: 4,021,569
Trainable params: 4,021,569
Non-trainable params: 0
_________________________________________________________________


In [ ]:
sampled_indices=tf.random.categorical(example_batch_predictions[0],num_samples=1)
sampled_indices = tf.squeeze(sampled_indices,axis=-1).numpy()

In [ ]:
sampled_indices

array([18, 35, 48, 49, 39, 44, 64, 39,  8, 64, 49, 16, 50, 58, 63, 24, 41,
       57, 45, 38, 26, 50,  8, 43, 34, 29,  4, 23,  6, 41,  8, 29, 30,  7,
       52, 59, 28, 52, 45, 51, 51, 49, 39, 51, 56, 15, 12, 62, 10, 41, 19,
       59, 51, 12, 31, 52, 31, 38, 32, 22, 43, 46, 41, 37, 51, 52, 28, 34,
       49, 36, 37, 21, 38, 28,  3, 61, 34, 63,  0, 61, 52, 64, 58, 53, 28,
       33, 16, 15, 60, 51, 40, 13, 40, 36, 54, 53, 10, 39,  7, 32])

In [ ]:
print("Input: \n", repr("".join(idx2char[input_example_batch[0]])))
print()
print("Next Char Predictions: \n", repr("".join(idx2char[sampled_indices ])))

Input: 
 "utinous; and it is rumour'd,\nCominius, Marcius your old enemy,\nWho is of Rome worse hated than of yo"

Next Char Predictions: 
 'FWjkafza.zkDltyLcsgZNl.eVQ&K,c.QR-nuPngmmkamrC?x:cGum?SnSZTJehcYmnPVkXYIZP$wVy\nwnztoPUDCvmbAbXpo:a-T'


In [ ]:
def loss(labels,logits):
  return tf.keras.losses.sparse_categorical_crossentropy(labels,logits,from_logits=True)
example_batch_loss=loss(target_example_batch,example_batch_predictions)
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)")
print("scalar_loss:      ", example_batch_loss.numpy().mean())

Prediction shape:  (64, 100, 65)  # (batch_size, sequence_length, vocab_size)
scalar_loss:       4.1743183


In [ ]:
model.compile(optimizer='adam',loss=loss)

In [ ]:
checkpoint_dir='./training_checkpoints'
checkpoint_prefix=os.path.join(checkpoint_dir,"ckpt_{epoch}")
checkpoint_callback=tf.keras.callbacks.ModelCheckpoint(filepath=checkpoint_prefix,save_weights_only=True)

In [ ]:
EPOCHS=10
history=model.fit(dataset,epochs=EPOCHS,callbacks=[checkpoint_callback])

Epoch 1/10
172/172 [==============================] - 7s 41ms/step - loss: 2.6462
Epoch 2/10
172/172 [==============================] - 7s 41ms/step - loss: 1.9515
Epoch 3/10
172/172 [==============================] - 7s 41ms/step - loss: 1.6877
Epoch 4/10
172/172 [==============================] - 7s 41ms/step - loss: 1.5409
Epoch 5/10
172/172 [==============================] - 7s 41ms/step - loss: 1.4540
Epoch 6/10
172/172 [==============================] - 7s 41ms/step - loss: 1.3953
Epoch 7/10
172/172 [==============================] - 7s 41ms/step - loss: 1.3488
Epoch 8/10
172/172 [==============================] - 7s 41ms/step - loss: 1.3104
Epoch 9/10
172/172 [==============================] - 7s 41ms/step - loss: 1.2767
Epoch 10/10
172/172 [==============================] - 7s 41ms/step - loss: 1.2443


In [ ]:
tf.train.latest_checkpoint(checkpoint_dir)

'./training_checkpoints/ckpt_10'

In [ ]:
model=build_model(vocab_size,embedding_dim,rnn_units,batch_size=1)
model.load_weights(tf.train.latest_checkpoint(checkpoint_dir))
model.build(tf.TensorShape([1,None]))


In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (1, None, 256)            16640     
_________________________________________________________________
gru_1 (GRU)                  (1, None, 1024)           3938304   
_________________________________________________________________
dense_1 (Dense)              (1, None, 65)             66625     
Total params: 4,021,569
Trainable params: 4,021,569
Non-trainable params: 0
_________________________________________________________________


In [ ]:
def generate_text(model, start_string):
    # Evaluation step (generating text using the learned model)

    # Number of characters to generate
    num_generate = 1000

    # Converting our start string to numbers (vectorizing)
    input_eval = [char2idx[s] for s in start_string]
    input_eval = tf.expand_dims(input_eval, 0)

    # Empty string to store our results
    text_generated = []

    # Low temperature results in more predictable text.
    # Higher temperature results in more surprising text.
    # Experiment to find the best setting.
    temperature = 1.0
    model.reset_states()
    for i in range(num_generate):
        predictions = model(input_eval)
        predictions = tf.squeeze(predictions, 0)
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)[-1,0].numpy()
        input_eval = tf.expand_dims([predicted_id], 0)

        text_generated.append(idx2char[predicted_id])

    return (start_string + ''.join(text_generated))



In [ ]:
example_batch_predictions[0].shape

TensorShape([100, 65])

In [ ]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [ ]:
sampled_indices

<tf.Tensor: shape=(100, 1), dtype=int64, numpy=
array([[62],
       [42],
       [12],
       [60],
       [24],
       [56],
       [38],
       [ 1],
       [15],
       [51],
       [ 7],
       [37],
       [ 0],
       [32],
       [48],
       [46],
       [42],
       [48],
       [30],
       [38],
       [29],
       [30],
       [40],
       [47],
       [58],
       [57],
       [20],
       [58],
       [17],
       [37],
       [30],
       [21],
       [31],
       [20],
       [ 7],
       [41],
       [24],
       [ 1],
       [64],
       [51],
       [18],
       [15],
       [54],
       [55],
       [ 1],
       [56],
       [ 6],
       [ 6],
       [20],
       [34],
       [26],
       [22],
       [22],
       [ 2],
       [ 9],
       [49],
       [60],
       [23],
       [ 6],
       [15],
       [34],
       [15],
       [25],
       [10],
       [41],
       [49],
       [ 8],
       [57],
       [ 8],
       [15],
       [43],
       [37],
       [23],
   

In [ ]:
aa=tf.argmax(example_batch_predictions[0][0],axis=-1)

In [ ]:
aa

<tf.Tensor: shape=(), dtype=int64, numpy=64>

In [ ]:
for i in example_batch_predictions[0][0]:
  print(i)
  break

tf.Tensor(-0.002006608, shape=(), dtype=float32)


In [ ]:
c=tf.argmax(example_batch_predictions[0][65])

In [ ]:
c

<tf.Tensor: shape=(), dtype=int64, numpy=24>

In [ ]:
example_batch_predictions[0][65]

<tf.Tensor: shape=(65,), dtype=float32, numpy=
array([ 0.00029799, -0.0018327 ,  0.00073117,  0.01142994, -0.00192412,
       -0.00757303,  0.00225865, -0.01609945,  0.01143583,  0.01764401,
       -0.01296948, -0.01150754,  0.01326837,  0.01601107, -0.00116881,
       -0.00037472,  0.0026346 ,  0.00493955,  0.00790331,  0.00383052,
       -0.00416242,  0.01049338,  0.01261466,  0.00793483,  0.02782   ,
       -0.00505296, -0.01110025, -0.00125062,  0.01024919,  0.00030212,
       -0.00936146, -0.00137215, -0.00160775, -0.01388822, -0.00114363,
       -0.00562447, -0.015834  ,  0.00203665, -0.00819761,  0.00357515,
       -0.00704474,  0.01187678,  0.01397098, -0.0003595 ,  0.01483709,
        0.00642386,  0.00716366,  0.01733554, -0.00813913, -0.01724182,
        0.01472687, -0.00172192,  0.0145547 ,  0.00332452,  0.01117037,
        0.00387043,  0.01245523,  0.01104997,  0.00397252,  0.00180487,
       -0.00106811, -0.00782063,  0.00305819, -0.00226292, -0.00710015],
      dtype=floa

In [ ]:
print(generate_text(model, start_string=u"ROMEO: "))

ROMEO: how now?

ISABELLA:
Pleay earnous.

MISHARD III:
I speak to thus.

NORTHUMBERLAND:
What makes your friends Capil, and what the deputy nor anger groom.
If He were petervast death at news
By all guilty, or was expediate thy tongue
And that thou keep's open, and see who case wainly a
chows of Edward leads did like talk'd ason he:
Is't, no more, or. what liar, I know
What come from the house of Larcius i' the island upon the wine,
And made your pleasure may I would be took
Have fault? I would not dear Milan; wortht my part,
Lest all fine and death'd to your comfort!

O does?

DORSET:
I am with my daughter.

LADY CAPULET:
O, and in thy common sword I stay that while

GOLZALO:
That shall grieve you tell them, do you quiet.

BUCKINGHAM:
God as Lord Stalliabter.

HORTENBIO:
Fear conceiving that they are stull, and let the silent Clarence call you
comes to-night;
Sirrah Grost Florizel will take theirs. re in men,
And in their temples in my partly sound.

GRENI:
And you dissente it in the

In [ ]:
@tf.function
def train_step(inp, target):
    with tf.GradientTape() as tape:
        predictions = model(inp)
        loss = tf.reduce_mean(
            tf.keras.losses.sparse_categorical_crossentropy(
                target, predictions, from_logits=True))
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

    return loss