<a href="https://colab.research.google.com/github/vivekvkashyap/Tensorflow/blob/main/IMDB_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow_datasets as tfds
import tensorflow as tf

In [ ]:
import tensorflow as tf
import keras
import numpy as np
import pandas as pd

In [ ]:
data=pd.read_csv('/content/drive/My Drive/dataset/IMDB Dataset 2.csv')

In [ ]:
data

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [ ]:
import re

In [ ]:
def preprocess(w):
  w=re.sub(r"([?.!,%&^%$#@])",r" ",w)
  w=re.sub(r'[" "]+'," ",w)
  w=re.sub(r"[^a-zA-Z?.!,]+"," ",w)
  w=w.strip()
  w='<start>'+w+'<end>'
  return w

In [ ]:
texts=[]

In [ ]:
for line in data['review']:
  a=preprocess(line)
  texts.append(a)


In [ ]:
len(texts)

50000

In [ ]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences

In [ ]:
max_len=256
max_words=10000


In [ ]:
tokenizer=Tokenizer(num_words=10000)
tokenizer.fit_on_texts(texts)
sequences=tokenizer.texts_to_sequences(texts)
word_index=tokenizer.word_index

In [ ]:
word_index

In [ ]:
len(word_index)

99426

In [ ]:
data1=pad_sequences(sequences,maxlen=max_len,padding='post')

In [ ]:
data1.shape

(50000, 256)

In [ ]:
labels=data['sentiment']

In [ ]:
labels.shape

(50000,)

In [ ]:
labels1=[]

In [ ]:
for i in labels:
  if i=='positive':
    j=1
    labels1.append(j)
  elif i=='negative':
    j=0
    labels1.append(j)



In [ ]:
labels2=np.asarray([labels1])

In [ ]:
labels2

array([[1, 1, 1, ..., 0, 0, 0]])

In [ ]:

labels2=labels2.reshape((50000, ))

In [ ]:
labels2.shape

(50000,)

In [ ]:
data1.shape

(50000, 256)

In [ ]:
labels2.shape

(50000,)

In [ ]:
data1

array([[ 267,    9,  206, ..., 4058,  480,   24],
       [  31,    3,  391, ...,    0,    0,    0],
       [  31,   10,  193, ...,    0,    0,    0],
       ...,
       [  31,   10,  232, ...,    0,    0,    0],
       [  31,   10,  140, ...,    0,    0,    0],
       [  31,   59,   30, ...,    0,    0,    0]], dtype=int32)

In [ ]:
labels2

array([1, 1, 1, ..., 0, 0, 0])

In [ ]:
train_data=data1[:40000]
train_labels=labels2[:40000]
val_data=data1[40000:]
val_labels=labels2[40000:]


In [ ]:
val_data.shape

(10000, 256)

In [ ]:
datasett=tf.data.Dataset.from_tensor_slices((train_data,train_labels))


In [ ]:
datasett2=tf.data.Dataset.from_tensor_slices((val_data,val_labels))

In [ ]:
val_data11=datasett2.batch(32).shuffle(10000)

In [ ]:
train_data11=datasett.batch(32).shuffle(40000)

In [ ]:
next(iter(val_data11))

(<tf.Tensor: shape=(32, 256), dtype=int32, numpy=
 array([[  27,   18, 1872, ..., 2915,   13,   24],
        [ 103,    7,    7, ...,   13,  379,   24],
        [  31,   30,   63, ...,    0,    0,    0],
        ...,
        [  31,   10, 1742, ...,    0,    0,    0],
        [  31,   15,    3, ...,    0,    0,    0],
        [  31,   11, 6708, ...,    0,    0,    0]], dtype=int32)>,
 <tf.Tensor: shape=(32,), dtype=int64, numpy=
 array([1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 0, 0,
        1, 0, 1, 0, 0, 1, 0, 1, 1, 1])>)

In [ ]:
next(iter(train_data11))

(<tf.Tensor: shape=(32, 256), dtype=int32, numpy=
 array([[  31,   10, 5904, ...,    0,    0,    0],
        [  31,   10,  113, ...,    0,    0,    0],
        [  31,  267,    9, ...,    0,    0,    0],
        ...,
        [  31,    1,  440, ...,    0,    0,    0],
        [  31,   10, 1004, ...,    0,    0,    0],
        [  31,   44,  212, ...,    0,    0,    0]], dtype=int32)>,
 <tf.Tensor: shape=(32,), dtype=int64, numpy=
 array([1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1,
        1, 0, 1, 1, 1, 1, 1, 1, 0, 1])>)

In [ ]:
from keras.models import Sequential
from keras.layers import Embedding,Flatten,Dense,LSTM
from keras import layers
import tensorflow as tf

In [ ]:
model1 = tf.keras.Sequential([
    tf.keras.layers.Embedding(10000, 128),
    tf.keras.layers.Bidirectional(tf.keras.layers.LSTM(64,return_sequences=True)),
    tf.keras.layers.LSTM(64,return_sequences=True),
    tf.keras.layers.LSTM(64),
 #   tf.keras.layers.LSTM(256))
   # tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(10000, 128),
    tf.keras.layers.LSTM(128,activation='relu',return_sequences=True),
    tf.keras.layers.LSTM(128,activation='relu'),
   # tf.keras.layers.LSTM(128),
    tf.keras.layers.Dense(128, activation='relu'),
    tf.keras.layers.Dense(1,activation='sigmoid')
])

In [ ]:
model1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 128)         1280000   
_________________________________________________________________
bidirectional_1 (Bidirection (None, None, 256)         263168    
_________________________________________________________________
lstm_3 (LSTM)                (None, 128)               197120    
_________________________________________________________________
dense_2 (Dense)              (None, 128)               16512     
_________________________________________________________________
dropout_1 (Dropout)          (None, 128)               0         
_________________________________________________________________
dense_3 (Dense)              (None, 1)                 129       
Total params: 1,756,929
Trainable params: 1,756,929
Non-trainable params: 0
____________________________________________

In [ ]:
import os

In [ ]:
os.makedirs('my_log_dir')

In [ ]:
callbacks1=[keras.callbacks.EarlyStopping(monitor='acc',patience='3',),keras.callbacks.ModelCheckpoint(filepath='my_model.h5',monitor='val_loss',save_best_only=True,),keras.callbacks.TensorBoard(log_dir='my_log_dir',histogram_freq=1,embeddings_freq=1,)]

In [ ]:
from keras import optimizers

In [ ]:
model.compile(loss=tf.keras.losses.BinaryCrossentropy(from_logits=True),
              optimizer=tf.keras.optimizers.Adam(1e-4),
              metrics=['accuracy'])

In [ ]:
history =model.fit(train_data11,epochs=10,validation_data=val_data11)

Epoch 1/10
1250/1250 [==============================] - 933s 747ms/step - loss: 0.6948 - accuracy: 0.5001 - val_loss: 0.6931 - val_accuracy: 0.4993
Epoch 2/10
 428/1250 [=========>....................] - ETA: 9:58 - loss: 0.6931 - accuracy: 0.5013