In [ ]:
2eimport tensorflow as tf
import keras
import pandas as pd
import numpy as np


In [ ]:
languages=[]
data=[]
x=[]
y=[]
with open('name2lang.txt','r') as f:
  for line in f:
    line=line.split(',')
    name=line[0].strip()
    lang=line[1].strip()
    if not lang in languages:
      languages.append(lang)
    x.append(name)
    y.append(lang)
    

In [ ]:
languages

In [ ]:
y[0:10]

In [ ]:
labels=[]

In [ ]:
for ll in y:
  if ll=='Portuguese':
    labels.append(1)
  elif ll=='Irish':
    labels.append(2)
  elif ll=='Spanish':
    labels.append(3)
  elif ll=='Vietnamese':
    labels.append(4)
  elif ll=='Chinese':
    labels.append(5)
  elif ll=='Greek':
    labels.append(6)
  elif ll=='Czech':
    labels.append(7)
  elif ll=='Dutch':
    labels.append(8)
  elif ll=='Japanese':
    labels.append(9)
  elif ll=='French':
    labels.append(10)
  elif ll=='German':
    labels.append(11)
  elif ll=='Scottish':
    labels.append(12)
  elif ll=='English':
    labels.append(13)
  elif ll=='Russian':
    labels.append(14)
  elif ll=='Polish':
    labels.append(15)
  elif ll=='Arabic':
    labels.append(16)
  elif ll=='Korean':
    labels.append(17)
  elif ll=='Italian':
    labels.append(18)

In [ ]:
len(labels)

20050

In [ ]:
labels[:10]

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1]

In [ ]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(char_level=True)
tokenizer.fit_on_texts(x)

In [ ]:
data=tokenizer.texts_to_sequences(x)

In [ ]:
data=tf.keras.preprocessing.sequence.pad_sequences(data,padding='post')

In [ ]:
data[:10]

array([[ 1, 16,  6,  3, 13,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 1, 10, 16, 13, 25, 13,  3,  6, 25, 13,  3,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 1, 10, 14,  3,  4, 15,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 1, 10, 11,  3,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 1,  6,  1, 13, 23,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [ 1,  6,  1, 13, 10, 10,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [16,  1,  6,  6,  2,  7,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [16,  1,  7, 13,  6, 12,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [16,  3, 10,  2,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0],
       [19,  1, 16,  6,  1, 10,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
         0,  0,  0]], dtype=int32)

In [ ]:
ddata=[]

In [ ]:
for vv in data:
  ddata.append(tf.one_hot(vv,depth=26))
  

In [ ]:
ddata[0]

<tf.Tensor: shape=(19, 26), dtype=float32, numpy=
array([[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.,

In [ ]:
llabel=[]

In [ ]:
for kk in labels:
  llabel.append(tf.one_hot(kk,depth=18))

In [ ]:
train_data=ddata[:15000]
train_label=llabel[:15000]
val_data=ddata[15000:]
val_label=llabel[15000:]


In [ ]:
train_data

In [ ]:
datasett=tf.data.Dataset.from_tensor_slices((train_data,train_label))

In [ ]:
datasett2=tf.data.Dataset.from_tensor_slices((val_data,val_label))

In [ ]:
datasett=datasett.batch(64).shuffle(150000)
datasett2=datasett2.batch(64)

In [ ]:
next(iter(datasett))

In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.LSTM(26,  return_sequences=True),
    tf.keras.layers.LSTM(32),
    tf.keras.layers.Dense(64, activation='relu'),
    tf.keras.layers.Dense(18)
])

In [ ]:
model.compile(optimizer='adam',loss=tf.keras.losses.CategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
model.fit(dataset1,epochs=30,validation_data=(datasett2))

Epoch 1/30
314/314 [==============================] - 5s 15ms/step - loss: 1.8915 - accuracy: 0.4617 - val_loss: 1.4165 - val_accuracy: 0.4174
Epoch 2/30
314/314 [==============================] - 4s 13ms/step - loss: 1.7053 - accuracy: 0.4680 - val_loss: 1.3238 - val_accuracy: 0.4174
Epoch 3/30
314/314 [==============================] - 4s 13ms/step - loss: 1.5460 - accuracy: 0.4973 - val_loss: 1.0676 - val_accuracy: 0.3717
Epoch 4/30
314/314 [==============================] - 4s 13ms/step - loss: 1.4277 - accuracy: 0.5427 - val_loss: 1.1286 - val_accuracy: 0.3610
Epoch 5/30
314/314 [==============================] - 4s 13ms/step - loss: 1.3707 - accuracy: 0.5499 - val_loss: 1.0503 - val_accuracy: 0.3650
Epoch 6/30
314/314 [==============================] - 4s 13ms/step - loss: 1.3562 - accuracy: 0.5547 - val_loss: 0.9899 - val_accuracy: 0.3830
Epoch 7/30
314/314 [==============================] - 4s 14ms/step - loss: 1.3284 - accuracy: 0.5504 - val_loss: 0.9336 - val_accuracy: 0.3723

In [ ]:
word="manteiga"


In [ ]:
#tokenizer.fit_on_texts(word)

In [ ]:
dd=tokenizer.texts_to_sequences("Archer")

In [ ]:
dd

[[1], [6], [19], [8], [3], [6]]

In [ ]:
dd=tokenizer.texts_to_sequences("archer")

In [ ]:
dd

[[1], [6], [19], [8], [3], [6]]

In [ ]:
dd=np.array([1,6,19,8,3,6])
dd

array([ 1,  6, 19,  8,  3,  6])

In [ ]:
ss=tf.one_hot(dd,depth=26)

In [ ]:
ss=tf.expand_dims(ss,axis=0)

In [ ]:
ss

<tf.Tensor: shape=(1, 6, 26), dtype=float32, numpy=
array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
         0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
model.predict(ss)

array([[ -8.696647 , -10.192931 ,  -4.505227 ,  -5.855137 ,  -7.3255844,
         -6.114259 ,  -1.1395855,  -2.143084 ,  -2.8953357,  -2.6241593,
         -5.3546267,  -2.3417354,  -9.153869 ,  -4.754699 ,  -0.8300557,
         -3.8538265,  -9.036219 ,  -7.000444 ]], dtype=float32)

In [ ]:
x=tf.nn.softmax(model.predict(ss))

In [ ]:
x

<tf.Tensor: shape=(1, 18), dtype=float32, numpy=
array([[1.7903051e-04, 3.8416903e-05, 9.7003253e-03, 2.6586489e-03,
        5.1023980e-04, 2.2572353e-03, 3.2145232e-01, 9.1083512e-02,
        4.7323778e-02, 6.1552715e-02, 4.5670024e-03, 8.6204447e-02,
        9.3544899e-05, 7.2239055e-03, 3.4835479e-01, 1.5751056e-02,
        1.1788543e-04, 9.3117799e-04]], dtype=float32)>